githubTag: null
githubCommit: null
in: /home/runner/data/exemplar-001
moduleIllum: [name:basic, container:labsyspharm/basic-illumination, version:1.1.0]
moduleRegistr: [name:ashlar, container:labsyspharm/ashlar, version:1.15.3]
moduleDearray: [name:coreograph, container:labsyspharm/unetcoreograph, version:2.2.8]
modulesPM: [[name:unmicst, container:labsyspharm/unmicst, version:2.7.4, cmd:python /app/unmicstWrapper.py --stackOutput --outputPath ., input:, watershed:yes], [name:cypository, container:labsyspharm/cypository, version:1.1.5, cmd:python /app/deployMaskRCNN.py --stackOutput --outputPath ., input:, watershed:bypass], [name:ilastik, container:labsyspharm/mcmicro-ilastik, version:1.4.5, cmd:python /app/mc-ilastik.py --output ., input:--input, model:--model, watershed:yes], [name:mesmer, container:vanvalenlab/deepcell-applications, version:0.3.0, cmd:python /usr/src/app/run_app.py mesmer --squeeze --output-directory . --output-name cell.tif, input:--nuclear-image, watershed:no]]
moduleSeg: [name:s3seg, container:labsyspharm/s3segmenter, version:1.3.18]
moduleQuant: [name:mcquant, container:labsyspharm/quantification, version:1.5.2]
modulesCS: [[name:naivestates, container:labsyspharm/naivestates, version:1.7.0, cmd:/app/main.R -o ., input:-i, model:--mct], [name:scimap, container:labsyspharm/scimap, version:0.17.7, cmd:scimap-mcmicro -o ., input:], [name:fastpg, container:labsyspharm/mc-fastpg, version:1.1.0, cmd:python3 /app/cluster.py -c, input:-i], [name:scanpy, container:labsyspharm/mc-scanpy, version:1.0.1, cmd:python3 /app/cluster.py -c, input:-i], [name:flowsom, container:labsyspharm/mc-flowsom, version:1.0.2, cmd:python3 /app/cluster.py -c, input:-i]]
roadie: labsyspharm/roadie:2022-03-14
ashlarOpts: -m 30
coreOpts: 
s3segOpts: 
quantOpts: --masks cell*.tif
unmicstOpts: 
cypositoryOpts: --model zeisscyto
ilastikOpts: --num_channels 1
mesmerOpts: 
naivestatesOpts: -p png
scimapOpts: 
fastpgOpts: 
scanpyOpts: 
flowsomOpts: 
contPfx: 
sampleName: exemplar-001
startAt: registration
stopAt: quantification
qcFiles: copy
tma: false
dynrange: false
multiFormats: {.xdce,.nd,.scan,.htd}
singleFormats: {.ome.tiff,.ome.tif,.rcpnl,.btf,.nd2,.tif,.czi}
probabilityMaps: unmicst
cellStates: scimap
illum: false
quantificationMask: 
maskSpatial: 
maskAdd: 
nstatesOpts: 
idxStart: 2
idxStop: 6
path_qc: /home/runner/data/exemplar-001/qc
path_prov: /home/runner/data/exemplar-001/qc/provenance
